### ISSUE TITLE
Loop freezes and nested prompts are not reachable

### ISSUE THREAD

**Issue by ibrahimovfuad** [nathanloisel/inquirer-recursive#3]
Hello.
I use plop for generation some stuff in project and I need recursive question in prompts array, but loop freezes after answering on the first question and then nothing happens.
Any thoughts?
`"plop": "^2.5.3",`
`"inquirer-recursive": "0.0.6",`

![Screenshot_1](https://user-images.githubusercontent.com/10096764/70545274-5db20b00-1b7e-11ea-9a00-c3f046ba4248.png)

![Screenshot_2](https://user-images.githubusercontent.com/10096764/70545560-d749f900-1b7e-11ea-8732-dfe34eea60f6.png)

**Comment by ibrahimovfuad** [comment]
Fixed by updating of the inquirer version to the latest for inquirer-recursive package.

**Comment by fabricioAburto** [comment]
I have the last version and I have the same problem....
